create table personas_perfiles(
	CODIGOPE VARCHAR(10),
    NOMBRES VARCHAR(50),
	APELLIDOS VARCHAR(50),
	GENERO VARCHAR(15),
	FECH_NACIMIENTO VARCHAR(15),
	FOTOGRAFIA VARCHAR(50)
);

Alter table personas_perfiles add constraint PK_CODIGOPE primary key (CODIGOPE);

create table roles(
	CODIGOROL VARCHAR(10),
    NOMBRE VARCHAR(50)
);

ALTER TABLE ROLES ADD CONSTRAINT PK_CODIGOROL PRIMARY KEY (CODIGOROL);

create table usuarios(
	CODIGOUS VARCHAR(10),
	USERNAME VARCHAR(20),
	EMAIL VARCHAR(255),
	PASSWORD VARCHAR(30),
	CODIGOPE VARCHAR(10)
);

ALTER TABLE USUARIOS ADD CONSTRAINT PK_CODIGOUS PRIMARY KEY (CODIGOUS);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_CODIGOPE FOREIGN KEY (CODIGOPE) REFERENCES PERSONAS_PERFILES(CODIGOPE);
ALTER TABLE USUARIOS ADD CONSTRAINT UK_CODIGOPE UNIQUE (CODIGOPE);

create table usuarios_roles(
	CODIGOUS VARCHAR(10) NOT NULL,
	CODIGOROL VARCHAR(10) NOT  NULL
);

ALTER TABLE USUARIOS_ROLES ADD CONSTRAINT PK_CODIGOUSROL PRIMARY KEY (CODIGOUS, CODIGOROL);
ALTER TABLE USUARIOS_ROLES ADD CONSTRAINT FK_USROL_CODIGOUS FOREIGN KEY (CODIGOUS) REFERENCES USUARIOS (CODIGOUS);
ALTER TABLE USUARIOS_ROLES ADD CONSTRAINT FK_USROL_CODIGOROL FOREIGN KEY (CODIGOROL) REFERENCES ROLES (CODIGOROL);

create table productos_custom(
	CODIGOPRCST VARCHAR(10),
    NOMBRE VARCHAR(50),
    FECHA_CREACION VARCHAR(20),
    PRECIO FLOAT,
    CODIGOUS VARCHAR(10),
    PISOS VARCHAR(10),
	IMG_REFERENCIAL VARCHAR(50)
);

ALTER TABLE productos_custom ADD CONSTRAINT PK_CODIGOPRCST PRIMARY KEY (CODIGOPRCST);
ALTER TABLE productos_custom ADD CONSTRAINT FK_CODIGOUS FOREIGN KEY (CODIGOUS) REFERENCES usuarios(CODIGOUS);

create table tipos_ingredientes(
	CODIGOTIPINGR VARCHAR(10),
    NOMBRE VARCHAR(20)
);

ALTER TABLE tipos_ingredientes ADD CONSTRAINT PK_TIPINGR PRIMARY KEY (CODIGOTIPINGR);

create table ingredientes(
	CODIGOINGR VARCHAR(10),
    NOMBRE VARCHAR(50),
    COSTO FLOAT,
    CODIGOTIPINGR VARCHAR(10)
);

ALTER TABLE ingredientes ADD CONSTRAINT PK_CODIGOINGR PRIMARY KEY (CODIGOINGR);
ALTER TABLE ingredientes ADD CONSTRAINT FK_CODIGOTIPINGR FOREIGN KEY (CODIGOTIPINGR) REFERENCES tipos_ingredientes(CODIGOTIPINGR);

create table productos_custom_ingredientes(
	CODIGOPRCST VARCHAR(10) NOT NULL,
    CODIGOINGR VARCHAR(10) NOT NULL
);

ALTER TABLE productos_custom_ingredientes ADD CONSTRAINT PK_CODIGOPRCSTINGR PRIMARY KEY (CODIGOPRCST, CODIGOINGR);
ALTER TABLE productos_custom_ingredientes ADD CONSTRAINT FK_PRCSTINGR_CODIGOPRCST FOREIGN KEY (CODIGOPRCST) REFERENCES productos_custom (CODIGOPRCST);
ALTER TABLE productos_custom_ingredientes ADD CONSTRAINT FK_PRCSTINGR_CODIGOINGR FOREIGN KEY (CODIGOINGR) REFERENCES ingredientes (CODIGOINGR);

create table pedidos(
	CODIGOPED VARCHAR(10),
    DIRECCION VARCHAR(100),
    TIPO_PAGO VARCHAR(20),
    MONTO_TOTAL FLOAT,
    FECHA_PEDIDO VARCHAR(20),
    CODIGOUS VARCHAR(10)
);

ALTER TABLE PEDIDOS ADD CONSTRAINT PK_CODIGOPED PRIMARY KEY (CODIGOPED);
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PED_CODIGOUS FOREIGN KEY (CODIGOUS) REFERENCES USUARIOS (CODIGOUS);

create table detalle_pedidos(
	CODIGODETPED VARCHAR(10),
    CODIGOPED VARCHAR(10),
    CODIGOPRCST VARCHAR(10),
    CANTIDAD VARCHAR(10),
    PRECIO FLOAT,
    DESCUENTO VARCHAR(10)
);

ALTER TABLE detalle_pedidos ADD CONSTRAINT PK_CODIGODETPED PRIMARY KEY (CODIGODETPED);
ALTER TABLE detalle_pedidos ADD CONSTRAINT FK_DETPED_CODIGOPED FOREIGN KEY (CODIGOPED) REFERENCES pedidos (CODIGOPED);
ALTER TABLE detalle_pedidos ADD CONSTRAINT FK_DETPED_CODIGOPRCST FOREIGN KEY (CODIGOPRCST) REFERENCES productos_custom (CODIGOPRCST);

commit;